#ifndef XS_SPLIT_STORE_FORWARD_H
#define XS_SPLIT_STORE_FORWARD_H

#include <stdint.h>

enum {
  XS_SPLIT_STORE_FLAG_ENTERED = 1u << 9,
  XS_SPLIT_STORE_FLAG_COMPLETED = 1u << 10,
  XS_SPLIT_STORE_SNIPPET_MAGIC = 0x53514657u,
  XS_SPLIT_STORE_RC_MISMATCH = 101,
};

#endif
