#ifndef XS_SCALAR_MISALIGN_H
#define XS_SCALAR_MISALIGN_H

#include <stdint.h>

enum {
  XS_SCALAR_MISALIGN_FLAG_LOAD_SPLIT_ENTERED = 1u << 20,
  XS_SCALAR_MISALIGN_FLAG_LOAD_SPLIT_COMPLETED = 1u << 21,
  XS_SCALAR_MISALIGN_FLAG_STORE_SPLIT_ENTERED = 1u << 22,
  XS_SCALAR_MISALIGN_FLAG_STORE_SPLIT_COMPLETED = 1u << 23,
  XS_SCALAR_MISALIGN_FLAG_CROSS_PAGE_ENTERED = 1u << 24,
  XS_SCALAR_MISALIGN_FLAG_CROSS_PAGE_COMPLETED = 1u << 25,
  XS_SCALAR_MISALIGN_FLAG_STORE_FORWARD_ENTERED = 1u << 26,
  XS_SCALAR_MISALIGN_FLAG_STORE_FORWARD_COMPLETED = 1u << 27,
  XS_SCALAR_MISALIGN_FLAG_STORE_FORWARD_SEARCH_ENTERED = 1u << 28,
  XS_SCALAR_MISALIGN_FLAG_STORE_FORWARD_SEARCH_COMPLETED = 1u << 29,
  XS_SCALAR_MISALIGN_FLAG_CROSS_PAGE_SEARCH_ENTERED = 1u << 30,
  XS_SCALAR_MISALIGN_FLAG_CROSS_PAGE_SEARCH_COMPLETED = 1u << 31,
  XS_SCALAR_MISALIGN_LOAD_SPLIT_MAGIC = 0x4d534c31u,
  XS_SCALAR_MISALIGN_STORE_SPLIT_MAGIC = 0x4d535331u,
  XS_SCALAR_MISALIGN_CROSS_PAGE_MAGIC = 0x4d534350u,
  XS_SCALAR_MISALIGN_STORE_FORWARD_MAGIC = 0x4d53464fu,
  XS_SCALAR_MISALIGN_STORE_FORWARD_SEARCH_MAGIC = 0x4d534653u,
  XS_SCALAR_MISALIGN_CROSS_PAGE_SEARCH_MAGIC = 0x4d534750u,
  XS_SCALAR_MISALIGN_REPLAY_PROBE_MAGIC = 0x4d535250u,
  XS_SCALAR_MISALIGN_CSR_TEMPLATE_COUNT = 40u,
  XS_SCALAR_MISALIGN_CSR_FAIL_CASE = 41u,
  XS_SCALAR_MISALIGN_CSR_CROSS_CAUSE0 = 42u,
  XS_SCALAR_MISALIGN_CSR_CROSS_CAUSE1 = 43u,
  XS_SCALAR_MISALIGN_CSR_CROSS_TVAL0 = 44u,
  XS_SCALAR_MISALIGN_CSR_CROSS_TVAL1 = 45u,
  XS_SCALAR_MISALIGN_CSR_FORWARD_VALUE0 = 46u,
  XS_SCALAR_MISALIGN_CSR_FORWARD_VALUE1 = 47u,
  XS_SCALAR_MISALIGN_CSR_PROBE_COUNT = 48u,
  XS_SCALAR_MISALIGN_CSR_PROBE_VALUE0 = 49u,
  XS_SCALAR_MISALIGN_CSR_PROBE_VALUE1 = 50u,
  XS_SCALAR_MISALIGN_CSR_PROBE_VALUE2 = 51u,
  XS_SCALAR_MISALIGN_LOAD_PAGE_CAUSE = 13u,
  XS_SCALAR_MISALIGN_STORE_ACCESS_CAUSE = 7u,
  XS_SCALAR_MISALIGN_RC_LOAD_SPLIT = 301,
  XS_SCALAR_MISALIGN_RC_STORE_SPLIT = 311,
  XS_SCALAR_MISALIGN_RC_CROSS_PAGE = 321,
  XS_SCALAR_MISALIGN_RC_STORE_FORWARD = 331,
  XS_SCALAR_MISALIGN_RC_STORE_FORWARD_SEARCH = 341,
  XS_SCALAR_MISALIGN_RC_CROSS_PAGE_SEARCH = 351,
  XS_SCALAR_MISALIGN_RC_REPLAY_PROBE = 361,
};

#endif
